#!/bin/bash
KRILL="krill"
DATA_DIR="/etc/krill"
LOG_DIR="/var/log"
KRILL_PID="$DATA_DIR/krill.pid"
CONF="$DATA_DIR/krill.conf"
SCRIPT_OUT="$LOG_DIR/krill.log"

nohup $KRILL -c $CONF >$SCRIPT_OUT 2>&1 &
echo $! > $KRILL_PID